### ISSUE TITLE
Display link to gallery on success (succeed loudly)

### ISSUE THREAD

**Issue by hugomd** [andreasmcdermott/micro-gallery#3]
On my machine, I run `gallery .` and it succeeds with no errors, but doesn't print anything like `Gallery running at http://localhost:3000/`. I think this would be a worthwhile addition, as I had to manually check to see if it was running correctly.

**Comment by hugomd** [comment]
I see that you display it if the `--dev` argument is given ([here](https://github.com/andreasmcdermott/micro-gallery/blob/master/bin/gallery.js#L190)), but I'm not sure of the reasoning for not doing it when running with no arguments given.

**Comment by andreasmcdermott** [comment]
Makes sense. I'll remove the check for dev and always output a link.

**Comment by andreasmcdermott** [comment]
Done here: https://github.com/andreasmcdermott/micro-gallery/commit/2870528792bef4c782cb50cb86695f9689c15a3c

**Comment by hugomd** [comment]
Thanks! :)
