### ISSUE TITLE
Demo source not visible for the unauthenticated users

### ISSUE THREAD

**Issue by d2s** [andreasmcdermott/micro-gallery#5]
Noticed that the *Demo source* is not visible for unauthenticated users.

When clicking the link URL [https://micro-gallery.now.sh/_src](https://micro-gallery.now.sh/_src) in the [README.md#demo-source](https://github.com/andreasmcdermott/micro-gallery/blob/596752b0588ed4911b834c78cad1f1f0be70bce6/README.md#demo-source) section, browser redirects to a Zeit login page.

![screenshot from 2018-02-04 01-11-17 micro-gallery now sh _src](https://user-images.githubusercontent.com/135053/35772489-5f71d08c-0948-11e8-88b3-fca7a2231e3b.png)

**Comment by andreasmcdermott** [comment]
Thanks for letting me know. I'll contact Zeit and see why that is the case.

**Comment by andreasmcdermott** [comment]
This should be fixed now.
